services:
  actual:
    # todo: lock to 25.12.0 once released
    image: ghcr.io/actualbudget/actual:edge
    container_name: actual
    restart: unless-stopped
    volumes:
      - ~/selfhosted/data/actual:/data
    networks:
      - swarmnet # port 5006

networks:
  swarmnet:
    external: true
    driver: overlay
