services:
  actual:
    image: ghcr.io/actualbudget/actual:25.11.0
    container_name: actual
    restart: unless-stopped
    volumes:
      - ~/selfhosted/data/actual:/data
    networks:
      - swarmnet # port 5006

networks:
  swarmnet:
    external: true
    driver: overlay
